name: Render README

on:
  push:
    branches: [master]

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: LATEST
      - name: Install R dependencies
        run:
          Rscript -e "install.packages('renv', repos = 'https://packagemanager.posit.co/cran/latest')"
          Rscript -e "renv::restore(repos = 'https://packagemanager.posit.co/cran/latest')"

      - name: Render Quarto document
        run:
          quarto render readme.qmd --to gfm --output README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}